### ISSUE TITLE
[2023-11-10]: [TekDriveAPIException when recreating Quickstart example]

### ISSUE THREAD

**Issue by jackparmer** [tektronix/tekdrive-sdk-python#10]
### Bug Summary

I receive the following API exception with the message, "should be a string" when trying to recreate `td.file.create("/path/to/file.txt", name="My New File")` from https://tektronix.github.io/tekdrive-sdk-python/quickstart/usage.html

> TekDriveAPIException: {'error_code': 'MALFORMED_INPUT', 'errors': [{'keyword': 'type', 'data_path': '.parentFolderId', 'schema_path': 'common#/definitions/uuidv4/type', 'params': {'type': 'string'}, 'message': 'should be string'}]}

I have verified that I'm using the correct TekDrive API key (for username is jp@flojoy.io)

### Steps to Reproduce
Add steps to reproduce this bug along with any other relevant information.

```
import tempfile
import os
print(tempfile.gettempdir()) # prints the current temporary directory

PATH = os.path.join(tempfile.gettempdir(), 'flojoy.txt')

try:
    f = open(PATH, 'x')
except:
    f = open(PATH, 'w')

f.write('asdf')

f.seek(0) # return to beginning of file

f.close()

td.file.create(PATH, name = 'My New File')
```

### Technical Details
* Python version: Python 3.11.5
* TekDrive version: 1.1.0 (you may also want to add a __version__ attribute to tekdrive)

**Comment by TJBIII** [comment]
Thanks for the detailed report @jackparmer. The fix is on the API side and is going through our deployment process now. I will follow up here once it is live on production.

**Comment by TJBIII** [comment]
The fix is live. Please let me know if you still have any issues. Thanks!

**Comment by jackparmer** [comment]
Perfect! Thank you!
